// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Pr$Reason99 = require("../src/Pr.bs.js");

describe("99 problems", (function () {
        return Jest.test("p01", (function () {
                      Jest.Expect[/* toEqual */12](/* Some */[47], Jest.Expect[/* expect */0](Pr$Reason99.last_element(/* :: */[
                                    12,
                                    /* :: */[
                                      21,
                                      /* :: */[
                                        47,
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
                      return Jest.Expect[/* toBe */2](/* None */0, Jest.Expect[/* expect */0](Pr$Reason99.last_element(/* [] */0)));
                    }));
      }));

/*  Not a pure module */
