// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function last_element_01(_ll) {
  while(true) {
    var ll = _ll;
    if (ll) {
      var rest = ll[1];
      if (rest) {
        _ll = rest;
        continue ;
        
      } else {
        return /* Some */[ll[0]];
      }
    } else {
      return /* None */0;
    }
  };
}

function last_two_02(_ll) {
  while(true) {
    var ll = _ll;
    if (ll) {
      var rest = ll[1];
      if (rest) {
        if (rest[1]) {
          _ll = rest;
          continue ;
          
        } else {
          return /* Some */[/* tuple */[
                    ll[0],
                    rest[0]
                  ]];
        }
      } else {
        return /* None */0;
      }
    } else {
      return /* None */0;
    }
  };
}

function at_03(_k, _ll) {
  while(true) {
    var ll = _ll;
    var k = _k;
    if (k !== 0) {
      if (ll) {
        _ll = ll[1];
        _k = k - 1 | 0;
        continue ;
        
      } else {
        return /* None */0;
      }
    } else if (ll) {
      return /* Some */[ll[0]];
    } else {
      return /* None */0;
    }
  };
}

exports.last_element_01 = last_element_01;
exports.last_two_02 = last_two_02;
exports.at_03 = at_03;
/* No side effect */
